[versions]
agp = "9.3.1"
kotlin = "2.4.10"
miuix = "0.9.3"
composeMp = "1.11.1"
coreKtx = "1.16.0"
activityCompose = "1.13.0"
lifecycle = "2.9.4"
exifinterface = "1.4.1"

[libraries]
miuix-ui = { module = "top.yukonga.miuix.kmp:miuix-ui", version.ref = "miuix" }
miuix-icons = { module = "top.yukonga.miuix.kmp:miuix-icons", version.ref = "miuix" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMp" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMp" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
